CREATE TABLE IF NOT EXISTS users (
                       user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email varchar(40) NOT NULL,
                       login varchar(40) NOT NULL,
                       user_name varchar(100),
                       birthday date CHECK (birthday < CURDATE())
);

CREATE TABLE IF NOT EXISTS status_friendship (
                                   status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   status_name varchar(40)
);

CREATE TABLE IF NOT EXISTS friends (
                         first_user_id integer REFERENCES users(user_id),
                         second_user_id integer REFERENCES users(user_id),
                         status_id integer REFERENCES status_friendship(status_id)
);

CREATE TABLE IF NOT EXISTS motion_picture_association (
                                            mpa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            mpa_name varchar(10)
);

CREATE TABLE IF NOT EXISTS films (
                       film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title varchar(40) NOT NULL,
                       description varchar(200),
                       release_date date CHECK (release_date > CAST('1895-12-28' AS date)),
                       duration integer CHECK (duration > 0),
                       motion_picture_association_id integer REFERENCES motion_picture_association(mpa_id)

);

CREATE TABLE IF NOT EXISTS genres (
                        genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        genre_name varchar(40)
);

CREATE TABLE IF NOT EXISTS film_genre (
                            film_id integer REFERENCES films(film_id),
                            genre_id integer REFERENCES genres(genre_id)
);

CREATE TABLE IF NOT EXISTS film_user (
                           film_id integer REFERENCES films(film_id),
                           user_id integer REFERENCES users(user_id)
);


insert into genres (genre_name)
VALUES ('Комедия');
insert into genres (genre_name)
VALUES ('Драма');
insert into genres (genre_name)
VALUES ('Мультфильм');
insert into genres (genre_name)
VALUES ('Триллер');
insert into genres (genre_name)
VALUES ('Документальный');
insert into genres (genre_name)
VALUES ('Боевик');

insert into motion_picture_association (mpa_name)
values ('G');
insert into motion_picture_association (mpa_name)
values ('PG');
insert into motion_picture_association (mpa_name)
values ('PG-13');
insert into motion_picture_association (mpa_name)
values ('R');
insert into motion_picture_association (mpa_name)
values ('NC-17');

insert into status_friendship(status_name)
values ('Не подтвержденный');
insert into status_friendship(status_name)
values ('Подтвержденный');



-- drop table users cascade;
-- drop table films cascade;
-- drop table film_user;
-- drop table status_friendship cascade;
-- drop table friends;
-- drop table genres cascade;
-- drop table film_genre;
-- drop table motion_picture_association cascade;
